// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQZJt-1gn8urEEQyG9wS6VRAOsrftOY0w',
    appId: '1:376865435309:web:15b3a8f1ed0690e2e12024',
    messagingSenderId: '376865435309',
    projectId: 'nepalsa-b1aa2',
    authDomain: 'nepalsa-b1aa2.firebaseapp.com',
    storageBucket: 'nepalsa-b1aa2.appspot.com',
    measurementId: 'G-EJ9KELC031',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFfRd_bA8oRL-N9qJuf4fi-wjxJAXxjDg',
    appId: '1:376865435309:android:a4af2bd9c67c8d14e12024',
    messagingSenderId: '376865435309',
    projectId: 'nepalsa-b1aa2',
    storageBucket: 'nepalsa-b1aa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0t4_8mFzFG9eGbOk2Kuv2Z-MNRv0BqjY',
    appId: '1:376865435309:ios:65ab91fa68c466aae12024',
    messagingSenderId: '376865435309',
    projectId: 'nepalsa-b1aa2',
    storageBucket: 'nepalsa-b1aa2.appspot.com',
    iosBundleId: 'com.example.nepalsa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0t4_8mFzFG9eGbOk2Kuv2Z-MNRv0BqjY',
    appId: '1:376865435309:ios:6e86642dd358404de12024',
    messagingSenderId: '376865435309',
    projectId: 'nepalsa-b1aa2',
    storageBucket: 'nepalsa-b1aa2.appspot.com',
    iosBundleId: 'com.example.nepalsa.RunnerTests',
  );
}
